### ISSUE TITLE
Ability To Earn Faster (Using functions for clicking) Read Below

### ISSUE THREAD

**Issue by DarkHeart527** [nullism/clickingbad#161]
All Cheaters And Boring People
Use the function setInterval( function() { gm.add_cash(1000000000000000000000) }, 1) in inspect element

**Comment by uygary** [comment]
Unfortunately, there's no way of preventing this from happening unless some sort of server-side implementation's added. And that would simply be over-kill.
Any client-side measures such as obfuscation etc. would be moot.
